from typing import Iterable

ROLE_PERMISSIONS = {
    "Admin": {
        "auth:login",
        "auth:me",
        "admin:users:read",
        "admin:users:write",
        "admin:roles:write",
        "audit:read",
        "project:create",
        "project:update",
        "project:read",
        "req:create",
        "req:read",
        "req:update",
        "req:delete",
        "req:versions:read",
        "req:comment:create",
        "req:comment:edit",
        "req:comment:delete",
        "req:status:change",
        "req:approve",
        "notif:read",
        "notif:mark_read",
        "trace:link:create",
        "trace:link:delete",
        "trace:link:read",
        "trace:rtm:read",
        "trace:impact:read",
        "trace:suspect:clear",
        "test:create",
        "test:update",
        "test:read",
        "verify:execute",
        "verify:read",
        "evidence:attach",
        "baseline:create",
        "baseline:read",
        "baseline:export",
        "import:upload",
        "import:review",
        "import:read",
        "standard:manage",
        "compliance:map",
        "compliance:read",
        "compliance:export",
    },
    "RequirementOwner": {
        "auth:login",
        "auth:me",
        "project:read",
        "req:create",
        "req:read",
        "req:update",
        "req:delete",
        "req:versions:read",
        "req:comment:create",
        "req:comment:edit",
        "req:comment:delete",
        "req:status:change",
        "notif:read",
        "notif:mark_read",
        "trace:link:create",
        "trace:link:delete",
        "trace:link:read",
        "trace:rtm:read",
        "trace:impact:read",
        "test:create",
        "test:update",
        "test:read",
        "verify:read",
        "baseline:create",
        "baseline:read",
        "baseline:export",
        "import:upload",
        "import:review",
        "import:read",
        "compliance:map",
        "compliance:read",
        "compliance:export",
    },
    "Reviewer": {
        "auth:login",
        "auth:me",
        "project:read",
        "req:read",
        "req:versions:read",
        "req:comment:create",
        "req:comment:edit",
        "req:comment:delete",
        "req:status:change",
        "notif:read",
        "notif:mark_read",
        "trace:link:read",
        "trace:rtm:read",
        "trace:impact:read",
        "test:read",
        "verify:execute",
        "verify:read",
        "evidence:attach",
        "baseline:read",
        "baseline:export",
        "import:read",
        "compliance:read",
        "compliance:export",
    },
    "Approver": {
        "auth:login",
        "auth:me",
        "project:read",
        "req:read",
        "req:versions:read",
        "req:comment:create",
        "req:comment:edit",
        "req:comment:delete",
        "req:status:change",
        "req:approve",
        "notif:read",
        "notif:mark_read",
        "trace:link:read",
        "trace:rtm:read",
        "trace:impact:read",
        "test:read",
        "verify:read",
        "baseline:read",
        "baseline:export",
        "import:read",
        "compliance:read",
        "compliance:export",
    },
    "Viewer": {
        "auth:login",
        "auth:me",
        "project:read",
        "req:read",
        "req:versions:read",
        "notif:read",
        "notif:mark_read",
        "trace:link:read",
        "trace:rtm:read",
        "test:read",
        "verify:read",
        "baseline:read",
        "baseline:export",
        "compliance:read",
        "compliance:export",
    },
}


def resolve_permissions(role_names: Iterable[str]) -> set[str]:
    permissions: set[str] = set()
    for role in role_names:
        permissions |= ROLE_PERMISSIONS.get(role, set())
    return permissions


def has_permission(role_names: Iterable[str], permission: str) -> bool:
    return permission in resolve_permissions(role_names)
